'use strict';
let state=Pension.defaults(),result,selectedYear,storeKey='pension-compass-v1';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const won=n=>Math.round(n).toLocaleString('ko-KR')+'원',man=n=>(n/10000).toLocaleString('ko-KR',{maximumFractionDigits:1})+'만원',large=n=>Math.abs(n)>=1e8?(n/1e8).toLocaleString('ko-KR',{maximumFractionDigits:2})+'억원':man(n);
function get(path){return path.split('.').reduce((o,k)=>o[k],state);}function set(path,v){const keys=path.split('.'),key=keys.pop();keys.reduce((o,k)=>o[k],state)[key]=v;}
function field(path,label,{type='number',scale=1,min=0,max,step='any',hint='',options}={}){const val=get(path),id='f-'+path.replaceAll('.','-');let control;
if(type==='select')control='<select id="'+id+'" data-path="'+path+'">'+options.map(([v,t])=>'<option value="'+v+'" '+(val===v?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select>';
else if(type==='checkbox')control='<input id="'+id+'" type="checkbox" data-path="'+path+'" '+(val?'checked':'')+'>';
else control='<input id="'+id+'" type="'+type+'" data-path="'+path+'" data-scale="'+scale+'" value="'+esc(type==='number'?Number((val/scale).toFixed(6)):val)+'" '+(type==='number'?'min="'+min+'" '+(max!==undefined?'max="'+max+'" ':'')+'step="'+step+'"':'maxlength="80"')+'>';
return '<div class="field '+(type==='checkbox'?'checkbox':'')+'">'+(type==='checkbox'?control:'')+'<label for="'+id+'">'+esc(label)+'</label>'+(type==='checkbox'?'':control)+(hint?'<small>'+esc(hint)+'</small>':'')+'</div>';}
const num=(path,label,min=0,max,step='any',hint='')=>field(path,label,{min,max,step,hint});const money=(path,label,hint='')=>field(path,label+' (만원)',{scale:10000,hint});const choose=(path,label,options)=>field(path,label,{type:'select',options});const check=(path,label)=>field(path,label,{type:'checkbox'});
function renderInputs(){
$('profileFields').innerHTML=num('profile.birth','출생연도',1900,2100,1)+num('profile.birthMonth','출생월',1,12,1)+num('profile.baseYear','계산 시작연도',2026,2150,1)+num('profile.endAge','종료 만 나이',55,120,1)+num('profile.inflation','물가상승률 (%)',-20,30)+money('profile.living','현재 기준 월 생활비');
$('taxFields').innerHTML=choose('profile.privateTax','사적연금 과세 선택',[['auto','자동 · 예상 세금 적은 방식'],['separate','분리과세'],['general','종합과세']])+money('profile.otherIncome','다른 연간 종합소득금액')+money('profile.deductions','연간 소득공제 합계','본인 기본공제 150만원 포함. 경로우대 등 직접 추가')+money('profile.taxCredit','국세 세액공제 합계','예시 7만원. 연금 외 소득이 있으면 적용 여부 확인');
$('healthFields').innerHTML=choose('profile.health','건강보험 자격',[['regional','지역가입자'],['employee','직장가입자'],['dependent','피부양자 검토']])+money('profile.healthOther','건보 다른 연간 부과소득','보수 외 소득/지역 세대 소득. 공단 기준에 맞춰 입력')+num('profile.healthOtherWeight','다른 부과소득 반영률 (%)',0,100)+money('profile.propertyPremium','건보 재산분 월액','지역가입 시 적용. 공단 산출액, 장기요양 제외')+money('profile.propertyTaxBase','피부양자 판단 재산과표','재산 시가가 아니라 재산세 과세표준')+money('profile.salaryPremium','기존 본인 보수보험료 월액','직장가입자만. 장기요양 제외, 본인 부담액')+check('profile.dependentOtherOK','사업소득·가족·배우자 등 기타 피부양자 요건 충족');
$('ruleFields').innerHTML=num('profile.healthRate','건강보험료율 (%)',.001,100)+num('profile.careRate','장기요양 소득 대비 요율 (%)',0,100,'any','보험료의 13.14%가 아니라 소득 대비 0.9448%')+money('profile.minHealth','건보 월 하한')+money('profile.maxHealth','건보 월 상한')+num('profile.publicWeight','공적연금 보험료 반영률 (%)',0,100)+money('profile.privateLimit','사적연금 분리과세 기준 / 연')+money('profile.dependentLimit','피부양자 소득 기준 / 연')+money('profile.employeeLimit','직장 보수 외 소득 공제 / 연');
$('nationalFields').innerHTML=money('national.monthly','정상 개시 시점 예상 월액','부양가족연금 포함 세전 금액')+num('national.shift','정상 대비 개시 개월',-60,60,1,'-60 = 5년 조기 / 0 = 정상 / 60 = 5년 연기')+num('national.increase','연금 연 인상률 (%)',-20,30);
$('nationalExtra').innerHTML=num('national.insuredMonths','예상 가입개월 · 추납 제외',0,1000,1)+num('national.taxable','연금 과세대상 비율 (%)',0,100,'any','2002년 이후 기여분 등 공단 과세대상 비율')+money('national.family','부양가족연금 월액','조기·연기 조정에서 제외')+money('national.workIncome','월평균 사업·근로소득금액','조기 수급 소득조건 확인용')+money('national.aValue','소득 있는 업무 기준 A값','2026년 319.3511만원. 해당 수급연도 값 확인')+money('national.manualReduction','공단 확인 월 감액','정상 소득활동 감액 등. 전 수령기간 고정 반영')+num('national.topupMonths','추납 개월',0,119,1)+money('national.topupCostPerMonth','추납 견적 월 보험료')+money('national.topupGain','추납 후 예상 월 증가액','공단 견적에서 추납 전·후 차이 입력')+money('national.topupSaving','추납 납부연도 절세액','소득공제로 실제 줄어드는 세금');
document.querySelector('[data-path="national.enabled"]').checked=state.national.enabled;
$('accounts').innerHTML=state.accounts.map((a,i)=>{const b='accounts.'+i+'.';return '<article class="panel account"><div class="sectionTitle"><span class="tag">'+(a.type==='account'?'연금계좌':'보험 약정액')+'</span><button class="textButton negative" data-remove="'+i+'">삭제</button></div><div class="fields">'+field(b+'name','연금 이름',{type:'text'})+choose(b+'type','연금 종류',[['account','퇴직연금·연금저축·IRP 계좌'],['insurance','개인연금보험 · 약정 월액']])+num(b+'startYear','수령 개시연도',state.profile.baseYear,2200,1)+num(b+'startMonth','개시월',1,12,1)+num(b+'years','수령기간 (년)',1,70,1)+(a.type==='account'?num(b+'rate','수수료 차감 후 연 수익률 (%)',-50,50)+choose(b+'mode','수령 방식',[['period','기간 맞춤 · 월액 자동 계산'],['fixed','월액 지정 · 고갈 확인']])+money(b+'monthly','지정 월 수령액','기간 맞춤에서는 이 값을 사용하지 않습니다')+money(b+'retired','퇴직금 원금 잔액')+money(b+'retirementTax','원금 대응 이연퇴직소득세','지방소득세 포함. 금융회사 확인 금액')+money(b+'excluded','공제받지 않은 원금 잔액')+money(b+'taxed','공제 납입금·운용수익 잔액') : money(b+'monthly','약정 월 지급액','종신보험은 종료 나이까지 충분한 기간을 입력')+num(b+'insuranceTax','전체 지급액 실효 최종 세율 (%)',0,100,'any','비과세는 0. 보험에 배분되는 최종 세금/전체 지급액 × 100'))+'</div><details><summary>과세 조건·건강보험 반영</summary><div class="fields">'+(a.type==='account'?num(b+'limitYear','첫 개시연도 한도 계산 연차',1,100,1,'최초 적격 기산연차·구계좌 예외를 금융회사에서 확인')+num(b+'actualYear','첫 개시연도 실제 수령연차',1,100,1,'퇴직금 70% / 60% / 50% 과세 판단')+check(b+'eligible','가입기간·개시신청 등 연금 요건 확인 (퇴직재원 예외 포함)')+check(b+'life','해지 불가 종신계약의 과세율 3.3% 적용'):'')+num(b+'healthWeight','건보 반영률 (%)',0,100,'any','사적연금 기본 0%. 개별 부과/향후 제도 가정')+'</div></details><div class="accountResult" id="account-result-'+i+'"></div></article>';}).join('');
}
function compute(){result=Pension.simulate(state);$('errors').hidden=!result.errors.length;if(result.errors.length){$('errors').innerHTML='<strong>계산을 위해 입력값을 확인해 주세요.</strong><ul>'+result.errors.map(e=>'<li>'+esc(e)+'</li>').join('')+'</ul>'; $('summary').innerHTML='';$('yearPreview').innerHTML='입력 오류를 수정하면 결과가 표시됩니다.';$('annualRows').innerHTML='';$('chart').innerHTML='';$('nationalComparison').innerHTML='';$('topupResult').innerHTML='';$('warnings').innerHTML='';document.querySelectorAll('.accountResult').forEach(e=>e.textContent='입력값 확인 필요');return;}
if(!result.rows.some(r=>r.year===selectedYear))selectedYear=result.rows[0].year;$('focusYear').innerHTML=result.rows.map(r=>'<option value="'+r.year+'" '+(r.year===selectedYear?'selected':'')+'>'+r.year+'년 · '+r.age+'세</option>').join('');
const r=result.rows.find(r=>r.year===selectedYear),tot=result.accounts.reduce((x,a)=>x+a.remaining,0);
$('summary').innerHTML=[['선택 연도 차감 후 월평균',man(r.net/r.months),r.year+'년 · 세금·건보·요양 차감'],['전체 기간 세전 수령액',large(result.totalGross),'계산 구간 '+result.rows.length+'개 연도 합계'],['전체 기간 세금·보험료',large(result.totalTax+result.totalHealth),'세금 '+large(result.totalTax)+' / 보험 '+large(result.totalHealth)],['전체 기간 순수령 · 추납 차감',large(result.totalAfterTopup),'종료 시 계좌 잔액 '+large(tot)]].map(([l,v,h])=>'<div class="metric"><label>'+l+'</label><strong>'+v+'</strong><small>'+h+'</small></div>').join('');
const bd=(l,v)=>'<div class="breakdown"><span>'+esc(l)+'</span><b>'+esc(v)+'</b></div>';
$('yearPreview').innerHTML='<div class="bigAmount">'+man(r.net/r.months)+'<small> / 월</small></div>'+bd('세전 국민연금 / 월',won(r.national/r.months))+bd('세전 사적연금 / 월',won((r.gross-r.national)/r.months))+bd('최종 연금 세금 추정 / 연',won(r.tax))+bd('건강보험 / 월',won(r.healthBase))+bd('장기요양 / 월',won(r.care))+bd('연금으로 늘어난 보험 / 월',won(r.healthAdded/r.months))+bd('과세 사적연금 합계 / 연',won(r.privateTaxable))+bd('사적연금 원천징수 / 연',won(r.withholding))+bd('사적연금 최종 세금 / 연',won(r.privateFinal))+bd('사적연금 예상 추가납부 / 연',won(r.settlement))+bd('선택 과세 방식',r.choice==='general'?'종합과세':'분리과세')+bd('물가 반영 월평균',man(r.real/r.months))+bd('생활비 대비 월 차이',man(r.gap/r.months))+'<p class="hint">'+esc(r.filing)+'<br>'+esc(r.healthStatus)+'</p><div class="bar"><span style="background:#1b5146;width:'+(r.gross>0?r.national/r.gross*100:0)+'%"></span><span style="background:#d2a85a;flex:1"></span></div>';
$('warnings').innerHTML=result.warnings.map(w=>'<div class="alert">'+esc(w)+'</div>').join('');
result.accounts.forEach((a,i)=>{const d=r.details[i],weight=state.accounts[i].healthWeight,allAssessed=r.details.reduce((s,d,j)=>s+d.gross*state.accounts[j].healthWeight/100,0),ownAssessed=d.gross*weight/100,hAll=Pension.health(r.national*12/r.months,allAssessed*12/r.months,state.profile),hWithout=Pension.health(r.national*12/r.months,(allAssessed-ownAssessed)*12/r.months,state.profile);$('account-result-'+i).innerHTML='<span>계산 월액 <b>'+man(a.monthly)+'</b></span><span>수령 합계 '+large(a.total)+' · 세금 추정 '+large(a.tax)+'</span><span>'+(a.depleted?'잔액 소진 '+a.depleted.year+'년 '+a.depleted.month+'월':'종료 시 잔액 '+large(a.remaining))+'</span><span>'+r.year+'년: 세전 '+man(d.gross)+' / 세금 '+man(d.tax)+' / 세후 '+man(d.gross-d.tax)+'</span><span>'+(weight===0?'건강보험 미반영 가정':'건보 반영 소득 '+man(ownAssessed)+' / 이 연금 추가 보험 '+won((hAll.annual-hWithout.annual)/12)+'/월')+'</span>';});
$('annualRows').innerHTML=result.rows.map(r=>'<tr><td>'+r.year+' / '+r.age+'세</td><td>'+won(r.gross)+'</td><td>'+won(r.tax)+'</td><td>'+won(r.health)+'</td><td><b>'+won(r.net/r.months)+'</b></td><td>'+won(r.real/r.months)+'</td><td class="'+(r.gap<0?'negative':'positive')+'">'+won(r.gap)+'</td><td>'+won(r.balance)+'</td><td>'+esc(r.filing)+'</td></tr>').join('');renderChart();renderComparison();
}
function renderChart(){const rows=result.rows,w=960,h=230,pad=45,values=rows.flatMap(r=>[r.gross/r.months,r.net/r.months]),min=Math.min(0,...values),max=Math.max(1,...values),x=i=>pad+(w-pad*2)*i/Math.max(1,rows.length-1),y=v=>h-30-(h-55)*(v-min)/(max-min),points=k=>rows.map((r,i)=>x(i).toFixed(2)+','+y(r[k]/r.months).toFixed(2)).join(' ');let ticks='';for(let j=0;j<4;j++){const val=min+(max-min)*j/3;ticks+='<line x1="'+pad+'" x2="'+(w-pad)+'" y1="'+y(val)+'" y2="'+y(val)+'" stroke="#e3e8de"/><text x="0" y="'+(y(val)+4)+'">'+Math.round(val/10000)+'만</text>';}[0,Math.floor((rows.length-1)/2),rows.length-1].forEach(i=>{ticks+='<text x="'+x(i)+'" y="225" text-anchor="middle">'+rows[i].year+'</text>';});$('chart').innerHTML='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="연도별 세전과 차감 후 월 연금 그래프">'+ticks+'<polyline points="'+points('gross')+'" fill="none" stroke="#d2a85a" stroke-width="3"/><polyline points="'+points('net')+'" fill="none" stroke="#1b5146" stroke-width="3"/></svg><div class="chartLegend"><span>● 세전 월평균</span><span style="color:#1b5146">● 차감 후 월평균</span></div>';}
function renderComparison(){if(!state.national.enabled){$('nationalComparison').innerHTML='<p>국민연금 계산을 켜면 비교 결과가 표시됩니다.</p>';$('topupResult').innerHTML='';return;}const comp=Pension.nationalCompare(state);$('nationalComparison').innerHTML=comp.scenarios.map((x,i)=>{const rr=x.result,title=['5년 조기','정상 수령','5년 연기'][i];if(rr.errors.length)return '<div class="scenario"><h3>'+title+'</h3><p>'+esc(rr.errors.join(' '))+'</p></div>';const factor=x.shift<0?1+x.shift*.005:1+x.shift*.006,n=state.national,monthly=(n.monthly-n.family+(n.topupMonths>0?n.topupGain:0))*factor+n.family;return '<div class="scenario '+(i===1?'normal':'')+'"><h3>'+title+'</h3><p>'+rr.nationalStart.year+'년 '+rr.nationalStart.month+'월 개시 · 정상 대비 '+Math.round((factor-1)*100)+'%</p><strong>'+man(monthly)+' / 월</strong><p>조정 기준 월액 · 인상·수동 감액 전</p><p>국민연금 세전 누계 <b>'+large(rr.rows.reduce((a,r)=>a+r.national,0))+'</b></p><p>전체 연금 순수령·추납 차감 <b>'+large(rr.totalAfterTopup)+'</b></p><p>정상 대비 누적 교차연도 <b>'+(i===1?'비교 기준':x.breakEven?x.breakEven+'년 ('+(x.shift<0?'정상이 역전':'연기가 역전')+')':'계산 기간 내 없음')+'</b></p></div>';}).join('');const t=comp.topup;$('topupResult').innerHTML='<h3 style="margin:0 0 12px">추납 효과 · 현재 선택 수령 시기 기준</h3><p>실질 추납 비용 <b>'+large(t.cost)+'</b> · 누적 순효과 <b class="'+(t.netGain<0?'negative':'positive')+'">'+large(t.netGain)+'</b> · 비용 회수 <b>'+(t.payback?t.payback+'년':t.cost===0?'추납 비용 없음':'계산 기간 내 미회수')+'</b></p><p class="hint">추납 전·후 전체 세후 연금과 보험료 차이를 비교한 뒤 추납 비용을 차감합니다.</p>';}
function notify(msg){$('message').textContent=msg;}
function download(name,text,mime){const url=URL.createObjectURL(new Blob([text],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function handleInput(e){const el=e.target;if(el.dataset.path){const path=el.dataset.path;let v=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?NaN:Number(el.value)*Number(el.dataset.scale||1)):el.value;set(path,v);if(path.endsWith('.type'))renderInputs();compute();notify('입력 변경을 반영했습니다. 보관하려면 입력 저장을 누르세요.');}}
document.addEventListener('change',handleInput);
document.addEventListener('input',e=>{if(e.target.tagName==='INPUT'&&e.target.type!=='checkbox'&&e.target.dataset.path)handleInput(e);});
document.addEventListener('click',e=>{const btn=e.target.closest('[data-tab]');if(btn){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!=='tab-'+btn.dataset.tab);}const rm=e.target.closest('[data-remove]');if(rm){state.accounts.splice(Number(rm.dataset.remove),1);renderInputs();compute();notify('연금을 삭제했습니다. 저장 전에는 기존 저장값을 불러올 수 있습니다.');}});
$('focusYear').addEventListener('change',()=>{selectedYear=Number($('focusYear').value);compute();});
$('add').onclick=()=>{if(state.accounts.length>=30)return notify('연금은 최대 30개입니다.');const a=structuredClone(Pension.defaults().accounts[1]);a.id='account-'+Date.now();a.name='새 연금';a.startYear=state.profile.baseYear;state.accounts.push(a);renderInputs();compute();};
$('save').onclick=()=>{if(result.errors.length)return notify('입력 오류를 수정한 후 저장하세요.');try{localStorage.setItem(storeKey,JSON.stringify(state));notify('입력값을 이 브라우저에 저장했습니다. 다른 기기에서 쓰려면 설정을 내려받으세요.');}catch{notify('브라우저 저장이 제한되어 있습니다. 설정 내려받기를 사용하세요.');}};
$('export').onclick=()=>{if(result.errors.length)return notify('입력 오류를 수정한 후 내려받으세요.');download('연금설계-설정.json',JSON.stringify(state,null,2),'application/json;charset=utf-8');};
$('import').onclick=()=>{$('file').click();};$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>1000000)throw Error('파일이 너무 큽니다.');const parsed=JSON.parse(await file.text());if(parsed.version!==Pension.VERSION)throw Error('지원하는 설정 파일 버전이 아닙니다.');const problems=Pension.validate(parsed);if(problems.length)throw Error(problems.join(' '));state=parsed;renderInputs();compute();notify('설정 파일을 불러왔습니다.');}catch(e){notify('불러오기 실패: '+e.message);}finally{$('file').value='';}};
$('reset').onclick=()=>{if(!confirm('현재 입력을 예시로 바꿀까요? 브라우저에 저장한 설정은 유지됩니다.'))return;state=Pension.defaults();renderInputs();compute();notify('예시 값으로 초기화했습니다.');};$('print').onclick=()=>window.print();
$('csv').onclick=()=>{if(result.errors.length)return notify('입력 오류를 먼저 수정하세요.');const header=['연도','만 나이(생일기준)','계산개월','국민연금 세전','전체 세전','연금 세금 추정','건강보험+장기요양','연금 증가 보험료','순수령','월평균 순수령','물가반영 연액','연 생활비','생활비 차이','계좌 잔액','사적 과세연금','사적 원천징수','사적 최종세금','사적 추가납부','과세선택','신고판단','건보판단'];const cell=v=>'"'+String(v).replaceAll('"','""')+'"';const lines=result.rows.map(r=>[r.year,r.age,r.months,...[r.national,r.gross,r.tax,r.health,r.healthAdded,r.net,r.net/r.months,r.real,r.living,r.gap,r.balance,r.privateTaxable,r.withholding,r.privateFinal,r.settlement].map(Math.round),r.choice,r.filing,r.healthStatus]);download('연금설계-연도별.csv','\uFEFF'+[header,...lines].map(line=>line.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
try{const saved=localStorage.getItem(storeKey);if(saved){const parsed=JSON.parse(saved);if(parsed.version===Pension.VERSION&&!Pension.validate(parsed).length){state=parsed;notify('이 브라우저에 저장된 입력값을 불러왔습니다.');}}}catch{}
renderInputs();compute();



