'use strict';
const {test,after,before}=require('node:test'),assert=require('node:assert/strict');
const {createServer}=require('./server');
let server,base;
before(async()=>{server=createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;});
after(async()=>{await new Promise(resolve=>server.close(resolve));});
test('preview serves the calculator entry point',async()=>{const response=await fetch(base+'/');assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/text\/html/);assert.match(await response.text(),/연금 나침반/);});
test('preview serves all runtime assets with appropriate content types',async()=>{for(const [name,type] of [['style.css','text/css'],['app.js','javascript'],['pension-engine.js','javascript']]){const response=await fetch(base+'/'+name);assert.equal(response.status,200);assert.ok(response.headers.get('content-type').includes(type));assert.ok((await response.text()).length>100);}});
test('private files and inherited object properties cannot be served',async()=>{for(const name of ['.git/config','.env','constructor','__proto__','README.md'])assert.equal((await fetch(base+'/'+name)).status,404);});
test('HEAD returns headers without a body',async()=>{const response=await fetch(base+'/',{method:'HEAD'});assert.equal(response.status,200);assert.equal(await response.text(),'');});
test('preview rejects writes and accepts query strings',async()=>{assert.equal((await fetch(base+'/',{method:'POST',body:'test'})).status,405);assert.equal((await fetch(base+'/?preview=1')).status,200);});
